### ISSUE TITLE
Tool tip for hovering over Disable Javascript does not appear consistently.

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#431] opened 2022-03-02 13:16 UTC
In testing the hovering of Disable Javascript under the View Menu when editing a template.  The tool tip that says "Turns off Javascript" appeared only once.  When I test this under Layout, Style and Content, does not make the tool tip appear when I hover over the View Menu option to Disable Javacript.

This was tested on Version 8.0.3 Build 105
See screenshots

![image-2022-02-18-09-13-17-325](https://user-images.githubusercontent.com/50147765/156368566-2609756e-8978-4e5f-8d3a-ab792d31b48f.png)

![image-2022-02-18-09-13-47-499](https://user-images.githubusercontent.com/50147765/156368559-c147c15d-f102-45ec-ab0c-09f505aae095.png)

![image-2022-02-18-09-14-25-010](https://user-images.githubusercontent.com/50147765/156368564-a4304bd4-a51b-4c70-b570-0c6b7adcdc81.png)

Note - the screenshots don't capture the Disable Javascript highlighted, but even when it is, the tool tip does not appear consistently.

Again, I saw the tool tip appear ONLY once

.

**Comment by natechadwick** [comment] 2023-08-30 15:49
Unable to reproduce on current version.  Marking as complete.

**Closed as completed by natechadwick** 2023-08-30 15:49 UTC
Labels: minor, Ready For QA
