### ISSUE TITLE
"Recent Assets" are not getting populated when adding a new asset from the Home Screen

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#440] opened 2022-03-02 14:25 UTC
This was reproduced on Version 8.0.3 Build 114

Behavior:  I have recently created assets as shown by created date in the Dashboard:

![image-2022-02-28-08-03-21-255](https://user-images.githubusercontent.com/50147765/156380051-a4a4bc4b-9011-46f2-bc6e-e1bf65722709.png)

I wanted to add a new asset from the homepage, but my recent assets are not showing under the "Recently added Assets" column.
![image-2022-02-28-08-04-43-013](https://user-images.githubusercontent.com/50147765/156380126-11dca38d-bf9b-4e8e-9ce3-477e6bde8376.png)

Also, no recent folder target locations are getting populated either
![image-20220228-130924](https://user-images.githubusercontent.com/50147765/156380214-1d5d2627-0f16-4a49-9e00-e8139a4b1e76.png)

Steps to reproduce:
1)  From the Home component - Click Add New button.
2)  Select the radio button for Asset - Click Next
3) Under choose an Asset Type - select the radio button "Recent Asset Types".    No asset types appear.
4)  Under Choose a Target location - Recent folders is also not returning results.

**Comment by natechadwick** [comment] 2023-08-30 15:41
Unable to reproduce on current version.  Marking as resolved.

**Closed as completed by natechadwick** 2023-08-30 15:41 UTC
Labels: Ready For QA
