### ISSUE TITLE
Broken rich text widget slots on imported template

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#571] opened 2022-07-28 13:56 UTC
**Describe the bug**
If a template has been imported from another instance, it is possible for the rich text widget slots to not work.  You can edit the slot but trying to save the changes will throw an error.  The same thing happens when dragging a rich text shared asset onto the widget slot.  

**Workarounds**
Removing and adding back the widget slot in the layout properties for a template seems to fix the problem

**To Reproduce**
1. Go to the Design section of the CMS

2. Click Actions > Import template

3. Import the attached template
[z-home-2022-template.txt](https://github.com/percussion/percussioncms/files/9214140/z-home-2022-template.txt)

4. In the Finder, click an asset folder.  Then click the create new asset button at the top right corner of the cms
<img width="463" alt="Screen Shot 2022-07-28 at 3 38 51 PM" src="https://user-images.githubusercontent.com/32443983/181636160-be0d1a7d-309e-4f8c-a912-b9d27c3e2706.png">

5. Select Rich Text Asset

6. Add any text to the asset along with a title and click Save

7. Go back to the Design section of the cms.  Edit the template that you imported

8. Click the Content tab on the template

9. While keeping the template editor open, navigate to the rich text asset you created in the Finder

10. Drag and drop the rich text asset onto this specific part of the template, where the widgets are stacked up.  May need to have the 🚫 appear before dropping the widget.
<img width="463" alt="Screen Shot 2022-07-28 at 3 38 51 PM" src="https://user-images.githubusercontent.com/32443983/181637973-278b370e-d53b-467e-afc2-40c234900cf2.png">
<img width="1080" alt="Screen Shot 2022-07-28 at 5 14 41 PM" src="https://user-images.githubusercontent.com/32443983/181638924-402fd0db-39ac-47bc-90a2-1a88d0ef71e2.png">

**Expected behavior**
There should be no errors on dragging assets to a template slot, if that template has been imported

**Screenshots**
Error on dragging asset to template
![image](https://user-images.githubusercontent.com/32443983/181520447-ff659d19-7840-4f8d-b462-96ca8b9c6ac4.png)

A 500 error is returned after making this call, but there is nothing in the error log on the server
![im1](https://user-images.githubusercontent.com/32443983/181521498-6792d37b-33ab-4677-9cfa-a75278bb6e7d.png)

**Comment by mariosm1** [comment] 2022-07-28 19:40
I'm able to reproduce the problem reliably with this template on 8.0.3 / 121.  It looks like it happens when you try to drag an asset to a set of stacked widgets (for example in this screenshot) - all text widgets on that page are broken after that.  Same issue does not happen in 8.1.
[z-home-2022-template.txt](https://github.com/percussion/percussioncms/files/9213629/z-home-2022-template.txt)
<img width="463" alt="Screen Shot 2022-07-28 at 3 38 51 PM" src="https://user-images.githubusercontent.com/32443983/181623361-b8ca97a4-57c5-466b-bd98-893b5a8b8663.png">

**Comment by natechadwick** [comment] 2022-07-29 13:30
@matomario8  Was unable to reproduce this on 8.1.1. We back ported a change to 8.0.3 release, https://github.com/percussion/percussioncms/pull/574/commits/a02b315ecd3f719f43b7f96e7046677223eeef1e,  that should fix this in 8.0.3.  Once the updated release kit finishes you should be able to verify.

**Comment by natechadwick** [comment] 2022-07-29 22:04
Closing this out as it looks resolved by 8.0.3 build 123

**Closed as completed by natechadwick** 2022-07-29 22:04 UTC
Labels: bug
