### ISSUE TITLE
Thumbnail for page does not display content on template

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#428] opened 2022-03-02 12:52 UTC
The thumbnail for a page does not show the content on the template when you preview it.  

This was tested on Version 8.0.3 Build 105.

Attached is a document that outlines the behavior.
(see below)

TEST RESULT:  The user should see the thumbnail for page on hovering on the preview icon for the page. The thumbnail should have title on top and page path on bottom. 

Follow up tests…The image appears when I do page preview for index.html after publishing, but the banner does not appear in this preview under the template.

 This was tested on 

[Step 4 CMS-3870.docx](https://github.com/percussion/percussioncms/files/8169660/Step.4.CMS-3870.docx)

**Comment by natechadwick** [comment] 2023-08-30 16:07
Can't reproduce so closing is done.

**Closed as completed by natechadwick** 2023-08-30 16:07 UTC
Labels: Can't Reproduce
