### ISSUE TITLE
Preview URL's drop the bookmark / anchor from the Preview link

### ISSUE THREAD

**Issue by natechadwick** [percussion/percussioncms#1250] opened 2024-04-03 14:38 UTC
**Describe the bug**

If you have links in an HTML widget that include # tags to link to sections in a page, the preview url drops the anchor (#) from the preview link. 

**To Reproduce**

1. Create a page with multiuple paragraphs, adding a # anchor link to the title line for each paragraph.
2. Add a new page and add an html widget to it. Add a list of links that link to each anchor on the test page. 
3. Preview the page with the HTML widget and click each link, notice that the anchor is not followed and is dropped from the Preview URL

**Expected behavior**
Preview urls should not drop anchor links so that anchor links work in preview. 

**Versions Affected**
* <= 8.1.4

**Comment by natechadwick** [comment] 2024-04-03 15:03
In testing this, when canonical links are set to sections on the site navigation, the # seems to get added after the section name on the location re-write, but the anchor is also not followed.

**Comment by rgarg24** [comment] 2024-05-07 16:41
Hi Nate,
We are not able to reproduce this issue. So, we can close this issue.

**Closed as completed by rgarg24** 2024-05-07 16:41 UTC
Labels: bug
