### ISSUE TITLE
Unable to login Workbench application if LDAP configuration is active for the connected CMS server and ldap connection is down.

### ISSUE THREAD

**Issue by kuldeepmalik** [percussion/percussioncms#544] opened 2022-03-02 08:14 UTC
**Note**: For ldap connection down, do not connect to the VPN for ldap machine.

Step 1: Configure LDAP setting and bring up the jetty server.
Step 2: Launch workbench application.
Step 3: Provide CMS server details, credentials of CMS database user and click on Connect button.
Step 4: Observe that application will keep showing connecting progress but never connects to the cms server.

![image](https://user-images.githubusercontent.com/77011198/156321000-2a51b38e-4f05-4b7d-8017-642e97b13d91.png)
[1646207702808.log](https://github.com/percussion/percussioncms-tools/files/8167816/1646207702808.log)
[server.log](https://github.com/percussion/percussioncms-tools/files/8167837/server.log)

**Comment by rgarg24** [comment] 2024-01-24 15:41
Hi Nate, I was unable to reproduce this issue. I think we can close this bug.

**Closed as completed** 2024-01-25 16:23 UTC
Labels: bug, Can't Reproduce
