### ISSUE TITLE
Tool Tip for Widgets only appears when the mouse is completely stopped when adding a widget to a template

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#432] opened 2022-03-02 13:31 UTC
Issue:  When hovering over a widget in a template, the tool tip does not appear unless the mouse is completely stopped.  In my case, the tool tip only appeared when I removed my hand from the mouse entirely.

This was tested on Version 8.0.3 Build 105

Steps to reproduce:

On the Designer tab - Put a template in Edit mode.

On the layout Tab - add a widget to a region on the template.

Hover over the widget.  Expected behavior is that a tool tip about the specific widget should appear.
![image-20220222-124826](https://user-images.githubusercontent.com/50147765/156371252-8289801e-483d-48dc-b1ad-3825f2dcb089.png)

**Comment by natechadwick** [comment] 2023-08-30 15:47
Unable to reproduce on current version.  Closing.

**Closed as completed by natechadwick** 2023-08-30 15:47 UTC
Labels: Ready For QA
