### ISSUE TITLE
Images are not uploading while importing the site.

### ISSUE THREAD

**Issue by ramdev1980** [percussion/percussioncms#1205] opened 2024-01-29 16:25 UTC
**Describe the bug**

While importing a site, the images are not being uploaded in Asset folder.

**To Reproduce**

1. Import a site (using Create Site).
2. Preview pages of the imported site.
3. Images are missing in html pages.

**Expected behavior**

All site images should be uploaded with site import.

**Comment by natechadwick** [comment] 2024-01-31 16:41
@ramdev1980  Are no images imported at all?

**Comment by natechadwick** [comment] 2024-02-21 17:44
Marking this as closed as the issue is resolved.

**Closed as completed by natechadwick** 2024-02-21 17:44 UTC
Labels: bug, Ready For QA
