### ISSUE TITLE
404 error in dashboard if a gadget doesn't exist

### ISSUE THREAD

**Issue by mariosm1** [percussion/percussioncms#767] opened 2023-05-09 15:21 UTC
**Describe the bug**
Removing a gadget from the system throws an error in the dashboard if that gadget was previously used.

**To Reproduce**
1. Use the dashboard in a version below 8.1.2.  Make sure the license monitor is on it.
2. Upgrade to version 8.1.2
3. Log in to the cms
4. 404 error should come up

**Expected behavior**
If a gadget does not exist anymore in the system, an error should not pop up in the front end.  Any references to the gadget should be quietly removed from the dashboard.

**Comment by sonydeswal74** [comment] 2023-12-01 15:38
I tried to reproduce this bug on 803 version upgraded to 814 and I was not able to reproduce it.

**Comment by rgarg24** [comment] 2023-12-01 15:40
Hi Nate,

I also tried to upgrade from 8.03 to 8.14 but I was not able to reproduce the bug.

**Comment by sonydeswal74** [comment] 2023-12-21 16:05
We were not able to reproduce it in 8.1.4 version. Thus closing the issue.

**Closed as completed** 2023-12-21 16:04 UTC
Labels: bug, minor
