### ISSUE TITLE
Incremental Publish Preview screen is cutting off the Last modified dates on the right side of screen

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#430] opened 2022-03-02 13:00 UTC
The Right hand side of the Incremental Publish Preview screen is getting cut off near the Last Modified column.  There is no scroll bar.

Steps to reproduce:
1)  On the Publishing pane, select the Site to publish
2)  Choose an incremental site to publish.  Click button and review the results of the Preview:

This was reproduced on Version 8.0.3 Build 77

![image-2021-12-29-18-07-09-141](https://user-images.githubusercontent.com/50147765/156366288-9a6bf127-5896-4ceb-b5b5-67a42cd73939.png)

**Comment by natechadwick** [comment] 2023-08-30 15:52
Unable to reproduce on current version.  See Horizontal and Vertical scrollbars now.  Closing.

![image](https://github.com/percussion/percussioncms/assets/1232206/51db7cf2-63a3-479e-ac4e-5102add5fb5c)

**Closed as completed by natechadwick** 2023-08-30 15:52 UTC
Labels: bug, Ready For QA
