### ISSUE TITLE
Revision History is out of synch with what is occurring on the Editor page in the Asset Finder

### ISSUE THREAD

**Issue by NxPerc2019** [percussion/percussioncms#444] opened 2022-03-02 15:48 UTC
This was reproduced on Version 8.0.3 Build 114

Behavior:  In the screenshot below - I have the file selected for Build 113, the editor is showing build105 test asset, and Revision History is for notinatemplate-1.png.

![image-2022-02-28-09-38-49-633](https://user-images.githubusercontent.com/50147765/156396567-4142335d-d370-4e4b-8e55-9f9ad6c6eb43.png)

This may be a single vs. double click and refresh issue.  

Steps to reproduce:
1)  In the Finder - select an asset and single click on it (Build113).  The page in the view navigates to it, the properties is showing from a previously selected asset (Build 105). 
![image-2022-02-28-09-53-25-183](https://user-images.githubusercontent.com/50147765/156396713-54383e00-eba4-446c-90f0-d285da9d56e1.png)

2)  Click Revision History and I see the revisions for Notatemplate.
![image-2022-02-28-09-54-19-335](https://user-images.githubusercontent.com/50147765/156396833-d09c44ff-3f91-4d6d-8983-76bb7469c929.png)

 This works better with double clicking through navigation.

**Comment by natechadwick** [comment] 2023-08-30 15:24
Closing as this is not a bug.

**Closed as completed by natechadwick** 2023-08-30 15:24 UTC
Labels: usability
